name: Bootcamp 2020

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installing Node
      uses: actions/setup-node@v2-beta
      with: 
        node version: 10
      - name: Installing
        run: npm install --global surge
      - name: deploying using surge 
        run : surge./ bootcamp2020smple.surge.sh --token ${{ secrets.SURGE_TOKEN }}